### PR TITLE
Group WMS layers

### PR DESCRIPTION
**Pull request by sterliakov**
This PR allows using single request to WMS server with multiple layers, grouped by corresponding URLs.

### CODE REVIEW

**Comment by sterliakov** [comment]
Merge conflicts are caused by using old v2.0.9 tag as requested.

**Comment by manisandro** [comment]
Can you better explain what the goal is, perhaps posting a sample request? Also, why only 2.0.9?

**Comment by sterliakov** [comment]
Honestly, I have no idea why v2.0.9 tag was requested, this is done under terms of Upwork contract. Perhaps I'm misunderstanding something regarding submission of completed work, sorry, let me re-check this with client first...

**Comment by dominik-modeso-ch** [comment]
Hi @manisandro I am the client mentioned in the comment above. Sorry for the confusion. This wasn't meant to end up as a PR on here, but rather on a fork which is based on v2.0.9.
If you are interested you are still welcome to use it of course, otherwise feel free to close this PR.

The intention behind this change to group WMS feature requests together into 1 if they are proxied to the same wms-service. This has significantly improved the performance in our use case where we had a lot of layers requested in the feature info and all but one went just to the local qgis-server.

**Pull request closed without merging**
